language: java
sudo: false
jdk:
  - oraclejdk8

script: mvn clean verify

notifications:
  slack: 
      secure: "tA2wRH+GKXY6IKMNGY2hP7BMsLiWiDJPTRlsiNIvlD6w7Zx0jX5cQ2rPmC1uckffx7yZAwkb+BIa7DIadsWauJBgIX9xqYalnQ54uU63ZV1gw/EryS/9u35546fudjG0zjukpdGgjA1KTKz2+OcIjBS80KUk7uW4tPaNg9zOzJ+sOs4gv6wm0gYt1KvlpNLAGP+YorTs0BXokCrUhVcE3HB3rs/6WWrLnMoiW0xIWOZiQi0VG/1gmWIhDxiF1YYAenMjkzrwcXGobnDHzeTwmMEoISuVuKOdfcx2cj+dnsmEVolBbhBbzQ/kua+mdMQeSTTqv23skgOjeSmBJjAruWD60W6tEV4T/CZgpwQH/W07WhfcikbrKlcxhkcFHDYGCjbdTCMwKkdy+enpMgQ6/SnBNoevIpic4pkKij+NJVNUmS39buewPJ/5CNamTAogNd8vZAXIB4rZqRvBcNmnTy4mVM+lH3y+z0XpSVe4L+YZFHJ/DjWmgKJKwYst0yaiJgiOu4X9UHJj5a3GmGZtwmpUlUNW/EeGNmAI6bLVAzsHGeefIIT1idwNLG/TL13+4inIJaOMZJWGt1s+9Pp7KLsMw17Vl1YjA2IxYH1kKAOANVjpqUs/9cN7c5Z5VNtbYzburRUkL59WPRGe0ttEFvB3C6MzT+mtJBMFtmW4UCU="
