package dev.thetechnokid.rw.net;

public enum Rank {
	NOOB, AIRMAN, AIRMAN_FIRST_CLASS, SENIOR_AIRMAN, SERGEANT, MASTER_SERGEANT, SENIOR_MASTER_SERGEANT, CHIEF_MASTER_SERGEANT, COMMAND_CHIEF_MASTER_SERGEANT, SECOND_LIEUTENANT, FIRST_LIEUTENANT, CAPTAIN, MAJOR, LIEUTENANT_COLONEL, COLONEL, BRIGADIER_GENERAL, MAJOR_GENERAL, LIEUTENANT_GENERAL, GENERAL, DICTATOR
}
